import type { CreatePrintConfigData, IPrintConfigRepository, UpdatePrintConfigData } from '@/core/domain/contracts';
import { PrintConfigEntity, type PrintOrientation } from '@/core/domain/entities';
import type { PrismaClient } from '@/generated/prisma/client';

export class PrismaPrintConfigRepository implements IPrintConfigRepository {
  constructor(private readonly db: PrismaClient) {}

  async findById(id: string): Promise<PrintConfigEntity | null> {
    const config = await this.db.printConfig.findUnique({
      where: { id },
    });

    if (!config) return null;

    return PrintConfigEntity.create({
      id: config.id,
      paperWidth: config.paperWidth,
      paperHeight: config.paperHeight,
      orientation: config.orientation as PrintOrientation,
      marginTop: config.marginTop,
      marginRight: config.marginRight,
      marginBottom: config.marginBottom,
      marginLeft: config.marginLeft,
      showFiventsLogo: config.showFiventsLogo,
      fiventsLogoPosition: config.fiventsLogoPosition,
      fiventsLogoSize: config.fiventsLogoSize,
      showOrgLogo: config.showOrgLogo,
      orgLogoPosition: config.orgLogoPosition,
      orgLogoSize: config.orgLogoSize,
      showQrCode: config.showQrCode,
      qrCodePosition: config.qrCodePosition,
      qrCodeSize: config.qrCodeSize,
      qrCodeContent: config.qrCodeContent,
      showName: config.showName,
      namePosition: config.namePosition,
      nameFontSize: config.nameFontSize,
      nameBold: config.nameBold,
      showCompany: config.showCompany,
      companyPosition: config.companyPosition,
      companyFontSize: config.companyFontSize,
      showJobTitle: config.showJobTitle,
      jobTitlePosition: config.jobTitlePosition,
      jobTitleFontSize: config.jobTitleFontSize,
      itemsOrder: config.itemsOrder,
      printerDpi: config.printerDpi,
      printerType: config.printerType,
      printSpeed: config.printSpeed,
      copies: config.copies,
      backgroundColor: config.backgroundColor,
      textColor: config.textColor,
      fontFamily: config.fontFamily,
      createdAt: config.createdAt,
      updatedAt: config.updatedAt,
    });
  }

  async create(data: CreatePrintConfigData): Promise<PrintConfigEntity> {
    const config = await this.db.printConfig.create({
      data: {
        paperWidth: data.paperWidth,
        paperHeight: data.paperHeight,
        orientation: data.orientation,
        marginTop: data.marginTop,
        marginRight: data.marginRight,
        marginBottom: data.marginBottom,
        marginLeft: data.marginLeft,
        showFiventsLogo: data.showFiventsLogo,
        fiventsLogoPosition: data.fiventsLogoPosition,
        fiventsLogoSize: data.fiventsLogoSize,
        showOrgLogo: data.showOrgLogo,
        orgLogoPosition: data.orgLogoPosition,
        orgLogoSize: data.orgLogoSize,
        showQrCode: data.showQrCode,
        qrCodePosition: data.qrCodePosition,
        qrCodeSize: data.qrCodeSize,
        qrCodeContent: data.qrCodeContent,
        showName: data.showName,
        namePosition: data.namePosition,
        nameFontSize: data.nameFontSize,
        nameBold: data.nameBold,
        showCompany: data.showCompany,
        companyPosition: data.companyPosition,
        companyFontSize: data.companyFontSize,
        showJobTitle: data.showJobTitle,
        jobTitlePosition: data.jobTitlePosition,
        jobTitleFontSize: data.jobTitleFontSize,
        itemsOrder: data.itemsOrder,
        printerDpi: data.printerDpi,
        printerType: data.printerType,
        printSpeed: data.printSpeed,
        copies: data.copies,
        backgroundColor: data.backgroundColor,
        textColor: data.textColor,
        fontFamily: data.fontFamily,
      },
    });

    return PrintConfigEntity.create({
      id: config.id,
      paperWidth: config.paperWidth,
      paperHeight: config.paperHeight,
      orientation: config.orientation as PrintOrientation,
      marginTop: config.marginTop,
      marginRight: config.marginRight,
      marginBottom: config.marginBottom,
      marginLeft: config.marginLeft,
      showFiventsLogo: config.showFiventsLogo,
      fiventsLogoPosition: config.fiventsLogoPosition,
      fiventsLogoSize: config.fiventsLogoSize,
      showOrgLogo: config.showOrgLogo,
      orgLogoPosition: config.orgLogoPosition,
      orgLogoSize: config.orgLogoSize,
      showQrCode: config.showQrCode,
      qrCodePosition: config.qrCodePosition,
      qrCodeSize: config.qrCodeSize,
      qrCodeContent: config.qrCodeContent,
      showName: config.showName,
      namePosition: config.namePosition,
      nameFontSize: config.nameFontSize,
      nameBold: config.nameBold,
      showCompany: config.showCompany,
      companyPosition: config.companyPosition,
      companyFontSize: config.companyFontSize,
      showJobTitle: config.showJobTitle,
      jobTitlePosition: config.jobTitlePosition,
      jobTitleFontSize: config.jobTitleFontSize,
      itemsOrder: config.itemsOrder,
      printerDpi: config.printerDpi,
      printerType: config.printerType,
      printSpeed: config.printSpeed,
      copies: config.copies,
      backgroundColor: config.backgroundColor,
      textColor: config.textColor,
      fontFamily: config.fontFamily,
      createdAt: config.createdAt,
      updatedAt: config.updatedAt,
    });
  }

  async update(id: string, data: UpdatePrintConfigData): Promise<PrintConfigEntity> {
    const config = await this.db.printConfig.update({
      where: { id },
      data: {
        paperWidth: data.paperWidth,
        paperHeight: data.paperHeight,
        orientation: data.orientation,
        marginTop: data.marginTop,
        marginRight: data.marginRight,
        marginBottom: data.marginBottom,
        marginLeft: data.marginLeft,
        showFiventsLogo: data.showFiventsLogo,
        fiventsLogoPosition: data.fiventsLogoPosition,
        fiventsLogoSize: data.fiventsLogoSize,
        showOrgLogo: data.showOrgLogo,
        orgLogoPosition: data.orgLogoPosition,
        orgLogoSize: data.orgLogoSize,
        showQrCode: data.showQrCode,
        qrCodePosition: data.qrCodePosition,
        qrCodeSize: data.qrCodeSize,
        qrCodeContent: data.qrCodeContent,
        showName: data.showName,
        namePosition: data.namePosition,
        nameFontSize: data.nameFontSize,
        nameBold: data.nameBold,
        showCompany: data.showCompany,
        companyPosition: data.companyPosition,
        companyFontSize: data.companyFontSize,
        showJobTitle: data.showJobTitle,
        jobTitlePosition: data.jobTitlePosition,
        jobTitleFontSize: data.jobTitleFontSize,
        itemsOrder: data.itemsOrder,
        printerDpi: data.printerDpi,
        printerType: data.printerType,
        printSpeed: data.printSpeed,
        copies: data.copies,
        backgroundColor: data.backgroundColor,
        textColor: data.textColor,
        fontFamily: data.fontFamily,
      },
    });

    return PrintConfigEntity.create({
      id: config.id,
      paperWidth: config.paperWidth,
      paperHeight: config.paperHeight,
      orientation: config.orientation as PrintOrientation,
      marginTop: config.marginTop,
      marginRight: config.marginRight,
      marginBottom: config.marginBottom,
      marginLeft: config.marginLeft,
      showFiventsLogo: config.showFiventsLogo,
      fiventsLogoPosition: config.fiventsLogoPosition,
      fiventsLogoSize: config.fiventsLogoSize,
      showOrgLogo: config.showOrgLogo,
      orgLogoPosition: config.orgLogoPosition,
      orgLogoSize: config.orgLogoSize,
      showQrCode: config.showQrCode,
      qrCodePosition: config.qrCodePosition,
      qrCodeSize: config.qrCodeSize,
      qrCodeContent: config.qrCodeContent,
      showName: config.showName,
      namePosition: config.namePosition,
      nameFontSize: config.nameFontSize,
      nameBold: config.nameBold,
      showCompany: config.showCompany,
      companyPosition: config.companyPosition,
      companyFontSize: config.companyFontSize,
      showJobTitle: config.showJobTitle,
      jobTitlePosition: config.jobTitlePosition,
      jobTitleFontSize: config.jobTitleFontSize,
      itemsOrder: config.itemsOrder,
      printerDpi: config.printerDpi,
      printerType: config.printerType,
      printSpeed: config.printSpeed,
      copies: config.copies,
      backgroundColor: config.backgroundColor,
      textColor: config.textColor,
      fontFamily: config.fontFamily,
      createdAt: config.createdAt,
      updatedAt: config.updatedAt,
    });
  }
}
