export enum ErrorCode {
  // ── Authentication ──────────────────────────────────────────────
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_ACCESS_CODE = 'INVALID_ACCESS_CODE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_SETUP_TOKEN = 'INVALID_SETUP_TOKEN',
  ADMIN_DOMAIN_NOT_ALLOWED = 'ADMIN_DOMAIN_NOT_ALLOWED',
  GOOGLE_OAUTH_FAILED = 'GOOGLE_OAUTH_FAILED',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  LOGIN_METHOD_UNAVAILABLE = 'LOGIN_METHOD_UNAVAILABLE',
  PASSWORD_NOT_CONFIGURED = 'PASSWORD_NOT_CONFIGURED',
  ACCESS_DISABLED = 'ACCESS_DISABLED',

  // ── Users ───────────────────────────────────────────────────────
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_SOFT_DELETED = 'USER_SOFT_DELETED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // ── Organizations ───────────────────────────────────────────────
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_ALREADY_EXISTS = 'ORGANIZATION_ALREADY_EXISTS',
  ORGANIZATION_ALREADY_ACTIVE = 'ORGANIZATION_ALREADY_ACTIVE',
  ORGANIZATION_ALREADY_INACTIVE = 'ORGANIZATION_ALREADY_INACTIVE',

  // ── Events ──────────────────────────────────────────────────────
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  EVENT_ALREADY_EXISTS = 'EVENT_ALREADY_EXISTS',
  EVENT_INVALID_TRANSITION = 'EVENT_INVALID_TRANSITION',

  // ── Totems ──────────────────────────────────────────────────────
  TOTEM_NOT_FOUND = 'TOTEM_NOT_FOUND',
  TOTEM_ACCESS_DENIED = 'TOTEM_ACCESS_DENIED',
  TOTEM_ALREADY_EXISTS = 'TOTEM_ALREADY_EXISTS',
  TOTEM_ALREADY_ACTIVE = 'TOTEM_ALREADY_ACTIVE',
  TOTEM_ALREADY_INACTIVE = 'TOTEM_ALREADY_INACTIVE',
  TOTEM_ALREADY_IN_MAINTENANCE = 'TOTEM_ALREADY_IN_MAINTENANCE',
  TOTEM_NOT_ACTIVE = 'TOTEM_NOT_ACTIVE',

  // ── Participants ────────────────────────────────────────────────
  PARTICIPANT_NOT_FOUND = 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_ALREADY_REGISTERED = 'PARTICIPANT_ALREADY_REGISTERED',

  // ── Check-in ────────────────────────────────────────────────────
  CHECKIN_DUPLICATE = 'CHECKIN_DUPLICATE',
  CHECKIN_LOW_CONFIDENCE = 'CHECKIN_LOW_CONFIDENCE',
  CHECKIN_CONFIDENCE_REQUIRED = 'CHECKIN_CONFIDENCE_REQUIRED',
  CHECKIN_SERVICE_ERROR = 'CHECKIN_SERVICE_ERROR',
  TOTEM_EVENT_SUBSCRIPTION_NOT_FOUND = 'TOTEM_EVENT_SUBSCRIPTION_NOT_FOUND',
  TOTEM_EVENT_SUBSCRIPTION_INACTIVE = 'TOTEM_EVENT_SUBSCRIPTION_INACTIVE',

  // ── Subscriptions ───────────────────────────────────────────────
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ALREADY_ACTIVE = 'SUBSCRIPTION_ALREADY_ACTIVE',
  SUBSCRIPTION_NOT_ACTIVE = 'SUBSCRIPTION_NOT_ACTIVE',

  // ── Plans ───────────────────────────────────────────────────────
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  PLAN_NOT_AVAILABLE = 'PLAN_NOT_AVAILABLE',
  PLAN_ALREADY_SELECTED = 'PLAN_ALREADY_SELECTED',
  PLAN_ALREADY_INACTIVE = 'PLAN_ALREADY_INACTIVE',

  // ── Plan Change Request ─────────────────────────────────────────
  PLAN_CHANGE_REQUEST_NOT_FOUND = 'PLAN_CHANGE_REQUEST_NOT_FOUND',
  PLAN_CHANGE_REQUEST_ALREADY_RESOLVED = 'PLAN_CHANGE_REQUEST_ALREADY_RESOLVED',
  PLAN_CHANGE_REQUEST_PENDING = 'PLAN_CHANGE_REQUEST_PENDING',

  // ── Membership ──────────────────────────────────────────────────
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',

  // ── Person ──────────────────────────────────────────────────────
  PERSON_NOT_FOUND = 'PERSON_NOT_FOUND',
  PERSON_ALREADY_EXISTS = 'PERSON_ALREADY_EXISTS',

  // ── Person Face ─────────────────────────────────────────────────
  PERSON_FACE_NOT_FOUND = 'PERSON_FACE_NOT_FOUND',
  PERSON_FACE_ALREADY_ACTIVE = 'PERSON_FACE_ALREADY_ACTIVE',
  PERSON_FACE_ALREADY_INACTIVE = 'PERSON_FACE_ALREADY_INACTIVE',

  // ── Feature ─────────────────────────────────────────────────────
  FEATURE_NOT_FOUND = 'FEATURE_NOT_FOUND',
  FEATURE_ALREADY_EXISTS = 'FEATURE_ALREADY_EXISTS',

  // ── Plan Feature ────────────────────────────────────────────────
  PLAN_FEATURE_NOT_FOUND = 'PLAN_FEATURE_NOT_FOUND',
  PLAN_FEATURE_ALREADY_EXISTS = 'PLAN_FEATURE_ALREADY_EXISTS',

  // ── Print Config ────────────────────────────────────────────────
  PRINT_CONFIG_NOT_FOUND = 'PRINT_CONFIG_NOT_FOUND',

  // ── Notification ────────────────────────────────────────────────
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // ── Audit Log ───────────────────────────────────────────────────
  AUDIT_LOG_NOT_FOUND = 'AUDIT_LOG_NOT_FOUND',

  // ── Totem Organization Subscription ─────────────────────────────
  TOTEM_ORG_SUBSCRIPTION_NOT_FOUND = 'TOTEM_ORG_SUBSCRIPTION_NOT_FOUND',
  TOTEM_ORG_SUBSCRIPTION_ALREADY_EXISTS = 'TOTEM_ORG_SUBSCRIPTION_ALREADY_EXISTS',
  TOTEM_NOT_AVAILABLE = 'TOTEM_NOT_AVAILABLE',

  // ── Totem Session ───────────────────────────────────────────────
  TOTEM_SESSION_NOT_FOUND = 'TOTEM_SESSION_NOT_FOUND',
  TOTEM_SESSION_EXPIRED = 'TOTEM_SESSION_EXPIRED',

  // ── Plan Limit Validation ───────────────────────────────────────
  PLAN_LIMIT_VALIDATION_ERROR = 'PLAN_LIMIT_VALIDATION_ERROR',

  // ── Totem Management ────────────────────────────────────────────
  TOTEM_MANAGEMENT_ERROR = 'TOTEM_MANAGEMENT_ERROR',

  // ── Validation ──────────────────────────────────────────────────
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  ENTITY_INVARIANT_VIOLATION = 'ENTITY_INVARIANT_VIOLATION',

  // ── Infrastructure ──────────────────────────────────────────────
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  AUTH_CONTEXT_MISSING = 'AUTH_CONTEXT_MISSING',

  // ── Generic ─────────────────────────────────────────────────────
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
