-- CreateEnum
CREATE TYPE "CodeSourceField" AS ENUM ('NONE', 'DOCUMENT', 'PHONE', 'EMAIL');

-- CreateEnum
CREATE TYPE "CodeProvenance" AS ENUM ('MANUAL', 'RANDOM', 'DERIVED');

-- AlterEnum (new AuditAction values for the batch settings actions)
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EVENT_AUTO_LINK_BACKFILL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PEOPLE_CODE_RECALCULATED';

-- Per-event toggle: automatically link newly created People to this event
ALTER TABLE "events" ADD COLUMN "auto_link_new_people" BOOLEAN NOT NULL DEFAULT false;

-- Track provenance of Person's own access code / QR code (manual vs random vs derived from a field)
ALTER TABLE "people"
ADD COLUMN "access_code_provenance" "CodeProvenance" NOT NULL DEFAULT 'RANDOM',
ADD COLUMN "qr_code_provenance" "CodeProvenance" NOT NULL DEFAULT 'RANDOM';

-- Track provenance of EventParticipant's own access code / QR code, independent of use_document_as_access_code
ALTER TABLE "event_participants"
ADD COLUMN "access_code_provenance" "CodeProvenance" NOT NULL DEFAULT 'RANDOM',
ADD COLUMN "qr_code_provenance" "CodeProvenance" NOT NULL DEFAULT 'RANDOM';

-- Backfill: codes that already exist today were not generated by the new derivation feature.
-- Mark them MANUAL so the future recalculation batch never rewrites pre-existing codes.
UPDATE "people" SET "access_code_provenance" = 'MANUAL' WHERE "access_code" IS NOT NULL;
UPDATE "people" SET "qr_code_provenance" = 'MANUAL' WHERE "qr_code_value" IS NOT NULL;
UPDATE "event_participants" SET "access_code_provenance" = 'MANUAL' WHERE "access_code" IS NOT NULL;
UPDATE "event_participants" SET "qr_code_provenance" = 'MANUAL' WHERE "qr_code_value" IS NOT NULL;

-- CreateTable
CREATE TABLE "organization_people_settings" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "access_code_source" "CodeSourceField" NOT NULL DEFAULT 'NONE',
    "qr_code_source" "CodeSourceField" NOT NULL DEFAULT 'NONE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "organization_people_settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "organization_people_settings_organization_id_key" ON "organization_people_settings"("organization_id");

-- AddForeignKey
ALTER TABLE "organization_people_settings" ADD CONSTRAINT "organization_people_settings_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
