import { z } from 'zod/v4';

const auditActionSchema = z.enum([
  'CHECK_IN',
  'CHECK_IN_APPROVED',
  'CHECK_IN_DENIED',
  'TOTEM_AUTH',
  'TOTEM_AUTH_SUCCESS',
  'TOTEM_AUTH_FAILED',
  'PARTICIPANT_CREATED',
  'PARTICIPANT_UPDATED',
  'PARTICIPANT_DELETED',
  'EVENT_CREATED',
  'EVENT_UPDATED',
  'EVENT_DELETED',
  'USER_LOGIN',
  'USER_LOGOUT',
  'FACE_REGISTERED',
  'FACE_UPDATED',
  'FACE_DELETED',
  'EXPORT_DATA',
  'IMPORT_DATA',
  'PRINT_CONFIG_CREATED',
  'PRINT_CONFIG_UPDATED',
  'TOTEM_CREATED',
  'TOTEM_UPDATED',
  'TOTEM_DELETED',
  'PLAN_CREATED',
  'PLAN_UPDATED',
  'PLAN_DELETED',
  'PLAN_CHANGE_REQUESTED',
  'PLAN_CHANGE_APPROVED',
  'PLAN_CHANGE_REJECTED',
  'USER_CREATED',
  'USER_UPDATED',
  'USER_DELETED',
  'USER_PASSWORD_RESET',
  'ORG_CREATED',
  'ORG_UPDATED',
  'ORG_DELETED',
  'ORG_ACTIVATED',
  'ORG_DEACTIVATED',
  'TOTEM_LINKED',
  'TOTEM_UNLINKED',
  'SUBSCRIPTION_CREATED',
  'SUBSCRIPTION_UPDATED',
  'SUBSCRIPTION_DELETED',
]);

export const createAuditLogRequestSchema = z.object({
  action: auditActionSchema,
  description: z.string().nullable().optional(),
  metadata: z.record(z.string(), z.unknown()).nullable().optional(),
  sessionId: z.string().nullable().optional(),
  organizationId: z.string().nullable().optional(),
  userId: z.string().nullable().optional(),
  eventId: z.string().nullable().optional(),
});

export type CreateAuditLogRequest = z.infer<typeof createAuditLogRequestSchema>;
